@Wbmcs.Api_HostAddress = http://localhost:5131

### Get all professors
GET {{Wbmcs.Api_HostAddress}}/professors
Accept: application/json

### Search professors via POST
POST {{Wbmcs.Api_HostAddress}}/professors/search?faculty=CS&name=Smith
Accept: application/json

### Search professors via GET
GET {{Wbmcs.Api_HostAddress}}/professors/search?faculty=CS&name=Smith
Accept: application/json